### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [WalleyWorks/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by WalleyWorks** [comment]
Thanks Ken. I tested the website on my desktop and it appeared responsive without the viewport meta tag, but noticed it appeared like the desktop version on my phone. I added the viewport meta tag to my head section. Let me know if that works.

**Comment by kenmazaika** [comment]
Thumbs up.  Great work. :+1:
